export type QuickSearchLocale = "es" | "en";

export const QUICK_SEARCH_COPY = {
  es: {
    back: "Atrás",
    title: "Búsqueda rápida",
    subtitle: "Encuentra rutas y guarda oportunidades en tu watchlist.",
    titleRecommendations: "Recomendaciones",
    subtitleRecommendations: "Selecciona países y descubre rutas ordenadas por valor.",
    workspaceHint: "Workspace de busqueda con filtros, ranking explicable y selector por país.",
    workspaceHintRecommendations: "Selecciona países o aeropuertos y ajusta filtros avanzados si quieres afinar.",
    originLabel: "Origen (IATA)",
    originTip: "Codigo IATA de 3 letras del aeropuerto.",
    originHelp: "Escribe el codigo o usa el selector por pais.",
    iataHelp: "Formato valido: 3 letras (ej: MAD).",
    iataInvalid: "El codigo IATA debe tener 3 letras.",
    originRequired: "Introduce un origen o elige un aeropuerto/pais.",
    destinationRequired: "Introduce un destino o elige un aeropuerto/pais.",
    iataSuggest: "Selecciona una sugerencia para evitar errores de codigo.",
    destinationLabel: "Destino (IATA)",
    destinationTip: "Si hay varias opciones, prueba un aeropuerto alternativo cercano.",
    destinationHelp: "Escribe el codigo o usa el selector por pais.",
    placeholderOrigin: "Ciudad o aeropuerto",
    placeholderDestination: "Ciudad o aeropuerto",
    placeholderDates: "Selecciona fechas",
    pickAirport: "Elegir aeropuerto",
    pickAirportOriginAria: "Elegir aeropuerto de origen",
    pickAirportDestinationAria: "Elegir aeropuerto de destino",
    pickCountryOnly: "Usar todo {country}",
    pickCountryOnlyHint: "Si eliges un país sin aeropuerto, buscaremos en todos sus aeropuertos.",
    countryOnlySelected: "País seleccionado: {country}",
    countryOnlyClear: "Quitar país",
    pickRecent: "Recientes",
    pickSearch: "Buscar aeropuerto o ciudad",
    pickEmpty: "No hay resultados con ese termino.",
    pickClose: "Cerrar",
    flexTitle: "Que margen tienes con la fecha?",
    daysBefore: "Dias antes",
    daysAfter: "Dias despues",
    exactDate: "Fecha exacta",
    flexible: "Flexible",
    flexHelper: "Elige primero una opcion rapida y personaliza solo si te hace falta.",
    flexHelperExact: "Buscaremos justo en la fecha elegida.",
    flexHelperFlexible: "Buscaremos salidas cercanas a tu fecha para encontrar mas opciones.",
    flexHelperCustom: "Ajusta por separado cuantos dias antes y despues quieres explorar.",
    flexPresetExact: "Exacta",
    flexPresetOne: "±1 dia",
    flexPresetTwo: "±2 dias",
    flexPresetThree: "±3 dias",
    flexPresetCustom: "Personalizar",
    flexCustomSummary: "Personalizado · -{before} / +{after} dias",
    flexBeforeControl: "Buscar desde",
    flexAfterControl: "Buscar hasta",
    flexApplyReturn: "Usar este mismo margen tambien para la vuelta",
    dateLabel: "Fecha",
    dateTip: "Elige la fecha exacta de salida.",
    roundTrip: "Ida y vuelta",
    returnLabel: "Vuelta",
    passengers: "Pasajeros adultos",
    search: "Buscar",
    searchHintRouteInvalid: "Introduce Origen y Destino validos para buscar",
    searchHintNeedDate: "Selecciona una fecha de salida para buscar",
    ready: "Listo para buscar",
    searchReadyTitle: "Listo para explorar",
    searchReadyText: "Introduce una ruta y pulsa Buscar para ver oportunidades.",
    searchReadyHint: "Puedes ampliar con aeropuertos cercanos y +/- dias si no hay resultados.",
    quickLookTitle: "Primer vistazo",
    quickLookBody: "Configura ruta, fecha y filtros, y luego pulsa Buscar para ver oportunidades.",
    quickLookAcknowledge: "Entendido",
    autocompleteSuggestionsAvailable: "{count} sugerencias disponibles",
    autocompleteNoSuggestions: "No hay sugerencias",
    summaryPassengersSingular: "pasajero",
    summaryPassengersPlural: "pasajeros",
    summaryRoundTrip: "Ida y vuelta",
    summaryRoundTripMissingReturn: "Ida y vuelta (falta vuelta)",
    summaryOneWay: "Solo ida",
    summaryRadius: "radio",
    summaryStrictOn: "Strict activo",
    summaryStrictOff: "Strict desactivado",
    summaryDurationMax: "Duracion max",
    summaryDurationOpen: "Duracion abierta",
    summaryExclusions: "Exclusiones",
    summaryMissingOrigin: "Falta origen",
    summaryMissingDestination: "Falta destino",
    summaryMissingDate: "Falta fecha",
    searchSummaryTitle: "Resumen de búsqueda",
    appliedCriteriaTitle: "Criterios aplicados",
    pendingChangesTitle: "Cambios sin aplicar",
    pendingChangesBody: "Pulsa Buscar para actualizar los resultados con tus criterios actuales.",
    applyAndSearch: "Aplicar y buscar",
    filtersTitle: "Filtros avanzados",
    filtersSubtitle: "Ajusta horarios, riesgo y reglas antes de buscar.",
    filtersMicrocopy: "Tip: si no hay resultados, prueba fechas cercanas y aeropuerto cercano.",
    filterConsoleEyebrow: "Control de filtros",
    filterConsoleTitle: "Consola de busqueda",
    filterConsoleSubtitle: "Define cuanto quieres abrir la busqueda y que resultados quieres ver sin perder el contexto.",
    filterCountLabel: "activos",
    filterNoActive: "Sin filtros extra: busqueda directa, horario amplio y resultados completos.",
    filterAppliedOnSearch: "Se aplica al buscar",
    filterAppliedToResults: "Ajusta la vista",
    filterPartialSupport: "Soporte parcial",
    filterCoverageDirect: "Solo ruta base",
    filterVisibleOpen: "Vista abierta",
    filterVisibleCustom: "Vista afinada",
    filterExperimentalOn: "Self-connect activo",
    filterExperimentalOff: "Directos primero",
    coverageTitle: "Cobertura",
    coverageBody: "Abre o limita aeropuertos alternativos y excluye IATA que no quieres usar.",
    visibleResultsTitle: "Resultados visibles",
    visibleResultsBody: "Filtra y ordena lo que ya ha devuelto la busqueda sin cambiar el contrato backend.",
    filterPresetDirect: "Directo",
    filterPresetDirectHint: "Origen y destino exactos.",
    filterPresetOriginNearby: "Abrir origen",
    filterPresetOriginNearbyHint: "Busca alternativas cerca del origen.",
    filterPresetBothNearby: "Abrir ambos",
    filterPresetBothNearbyHint: "Explora origen y destino cercanos.",
    filterPresetRegional: "Regional",
    filterPresetRegionalHint: "Radio amplio para descubrir mas combinaciones.",
    resetGroup: "Restablecer grupo",
    appliedPref: "Aplicado desde tus preferencias",
    alternatesTitle: "Alternativos y cobertura",
    radiusLabel: "Radio alternativo (km)",
    radiusHint: "Incluye aeropuertos cercanos; valores altos pueden aumentar el tiempo.",
    radiusInactive: "Activa origenes o destinos cercanos para usar el radio.",
    priceMin: "Precio minimo",
    priceMax: "Precio maximo",
    nearbyOrigins: "Incluir origenes cercanos",
    nearbyDestinations: "Incluir destinos cercanos",
    timeTitle: "Tiempo y viabilidad",
    timeSubtitle: "Controla franja y duracion total.",
    departAfter: "Salida desde",
    departBefore: "Salida hasta",
    durationMax: "Duracion maxima (min)",
    strictMode: "Modo estricto (sin relajacion)",
    strictWarning: "Viru puede relajar horarios si no hay resultados. Desactiva si quieres explorar mas opciones.",
    stopsTitle: "Escalas y exclusiones",
    stopsSubtitle: "Self-connect requiere margen.",
    includeStops: "Incluir escalas (self-connect)",
    maxStops: "Maximo de escalas",
    riskAllowed: "Riesgo permitido",
    bufferMin: "Buffer minimo (min)",
    bufferMinHint: "Margen recomendado entre tramos.",
    excludeOrigins: "Excluir origenes (IATA)",
    excludeDestinations: "Excluir destinos (IATA)",
    selfConnectWarning: "Conexion autogestionada: revisa buffer y riesgo antes de comprar.",
    resetPrefs: "Restablecer a mis preferencias",
    resetAll: "Restablecer todo",
    deepLink: "Abrir en Ryanair",
    deepLinkAlt: "Copiar parametros",
    deepLinkModalTitle: "Sin enlace directo",
    deepLinkModalBody: "No se pudo generar enlace directo. Copia la busqueda o abre Ryanair manualmente.",
    deepLinkCopy: "Copiar parametros",
    deepLinkCopied: "Parametros copiados",
    loadingFlight: "cargando vuelo",
    loadingAria: "Cargando",
    loadingTitle: "Buscando vuelos...",
    loadingText: "Probando alternativos y flexibilidad de fechas para encontrar opciones.",
    loadingPhaseRequesting: "Consultando tarifas...",
    loadingPhaseResponseParsed: "Ordenando resultados...",
    loadingPhaseClientDone: "Preparando vista...",
    loadingPhaseCommitted: "Listo",
    loadingSubcheckTitle: "Comprobaciones en curso",
    loadingSubcheckFlight: "Buscando vuelo {route}",
    loadingSubcheckCombo: "Buscando mejor combinacion {index}/{total}",
    loadingSubcheckActive: "en curso",
    loadingSubcheckDone: "completado",
    loadingTotalFlights: "Vuelos a buscar: {count}",
    loadingProgressFlights: "Progreso: {current}/{total} vuelos",
    loadingScope: "Cobertura activa: {routes} rutas x {days} dias",
    modalOriginCountry: "Pais de origen",
    modalDestinationCountry: "Pais de destino",
    modalPickTitle: "Elegir aeropuerto",
    modalClear: "Borrar seleccion",
    weatherTitle: "Clima previsto",
    weatherSubtitle: "Origen y destino para cada fecha seleccionada",
    weatherOrigin: "Origen",
    weatherDestination: "Destino",
    weatherDepart: "Salida",
    weatherArrive: "Llegada",
    weatherClear: "Despejado",
    weatherMostlyClear: "Poco nuboso",
    weatherCloudy: "Nublado",
    weatherFog: "Niebla",
    weatherDrizzle: "Llovizna",
    weatherRain: "Lluvia",
    weatherSnow: "Nieve",
    weatherShowers: "Chubascos",
    weatherStorm: "Tormenta",
    weatherVariable: "Variable",
    explainTitle: "Como ordenamos",
    explainSubtitle: "Ranking heuristico basado en precio, desvio de fecha, distancia y riesgo.",
    explainPriceTitle: "Precio",
    explainTimeTitle: "Desviacion temporal",
    explainAltTitle: "Alternativos",
    explainRiskTitle: "Riesgo",
    explainPrice: "Prioriza oportunidades con mejor valor relativo.",
    explainTime: "Menor distancia a tu fecha objetivo.",
    explainAlt: "Distancia terrestre y facilidad de acceso.",
    explainRisk: "Self-connect con buffer bajo reduce prioridad.",
    disclaimer: "Busqueda rapida en modo heuristico. Precio orientativo base 1 adulto sin extras.",
    disclaimerWatchlistCta: "Guarda en watchlist para cambios.",
    degraded: "Proveedor no disponible temporalmente. Mostramos ultimo dato confirmado.",
    degradedBadge: "Modo degradado",
    degradedChip: "Heuristico",
    degradedHint: "Si el proveedor no responde, mostramos el ultimo dato confirmado.",
    filtersRelaxed: "Se relajaron filtros",
    relaxedDateFlexAuto: "flexibilidad de fecha automatica",
    relaxedNearbyAuto: "ampliacion automatica a aeropuertos cercanos",
    relaxedDepartureWindowAuto: "franja horaria ampliada automaticamente",
    results: "resultados",
    orderedBy: "ordenados por",
    orderBy: "Ordenar por",
    toolbarFilters: "Filtros",
    toolbarExplain: "Como ordenamos",
    toolbarCompact: "Vista compacta",
    toolbarExpanded: "Vista detallada",
    toolbarActiveFilters: "Filtros activos",
    infoSectionTitle: "Informacion",
    viewDetail: "Ver detalle",
    warningDetailsOpen: "Ver detalles",
    warningDetailsClose: "Ocultar detalles",
    warningsGroupedTitle: "Avisos",
    warningProblemTitle: "Problema",
    providerPartialAvailabilityNotice: "Mostramos resultados confirmados, pero faltan respuestas de disponibilidad en parte de Ryanair.",
    providerPartialFaresNotice: "Mostramos resultados confirmados, pero faltan respuestas de tarifas en parte de Ryanair.",
    providerPartialMixedNotice: "Mostramos resultados confirmados, pero Ryanair respondio de forma parcial en esta busqueda.",
    emptyStateMainTitle: "0 resultados con estos filtros",
    emptyStateProviderTitle: "Ryanair no respondio ahora mismo",
    emptyStateProviderPartialTitle: "Busqueda parcial: faltan respuestas de Ryanair",
    emptyShowMore: "Ver más",
    emptyShowLess: "Ver menos",

    rowActionsMoreAria: "Abrir más acciones",
    rowActionsMenuAria: "Acciones adicionales del resultado",
    ariaFiltersToggle: "Filtros ({count})",
    ariaRemoveFilter: "Eliminar {value}",
    resultsColRoute: "Ruta",
    resultsColPrice: "Precio",
    resultsColDuration: "Duracion",
    resultsColRisk: "Riesgo",
    resultsColFreshness: "Frescura",
    resultsColActions: "Acciones",
    sortRanking: "Ranking",
    sortPrice: "Precio",
    sortDuration: "Duracion",
    sortRisk: "Riesgo",
    sortFreshness: "Frescura",
    sortFreshnessHint: "Ultima actualizacion",
    riskAll: "Todos",
    riskLow: "Bajo",
    riskMedium: "Medio",
    riskHigh: "Alto",
    riskHidden: "Ocultadas (riesgo alto)",
    riskShowHidden: "Mostrar riesgo alto",
    riskHideHidden: "Ocultar riesgo alto",
    stopsOne: "1 escala",
    stopsTwo: "2 escalas",
    startSearch: "Lanza una busqueda para ver oportunidades.",
    noResultsFilters: "No hay resultados con estos filtros.",
    relaxFilters: "Relajar filtros",
    emptyTitle: "No hay resultados con estos filtros.",
    emptyText: "Prueba a relajar restricciones o ampliar el radio.",
    stateEmptyHint: "Ajusta filtros o usa una accion rapida para recuperar resultados.",
    stateErrorHint: "Revisa los datos del formulario y vuelve a intentarlo.",
    stateRateHint: "Hemos limitado temporalmente la frecuencia para proteger el servicio.",
    emptyCta: "Relajar filtros",
    relaxPreviewTitle: "Cambios propuestos",
    relaxPreviewImpact: "Estos cambios pueden mostrar más resultados.",
    relaxPreviewConfirm: "Aplicar cambios y buscar",
    relaxPreviewCancel: "Cancelar",
    relaxPreviewNoChanges: "No hay cambios propuestos con la configuración actual.",
    emptyLikelyCausesTitle: "Causas probables",
    emptyRelaxActionsTitle: "Prueba rapido",
    emptyCauseStrict: "Modo estricto activo (sin relajacion).",
    emptyCauseDuration: "Duracion maxima ajustada puede estar filtrando rutas.",
    emptyCauseTimeWindow: "La franja horaria de salida es estrecha.",
    emptyCauseRadius: "Cobertura de radio limitada para alternativos.",
    emptyCauseExclusions: "Hay aeropuertos excluidos que reducen opciones.",
    emptyCauseStops: "No se permiten escalas (solo directos).",
    emptyCauseProvider: "El proveedor no respondio y no pudimos confirmar vuelos ahora mismo.",
    emptyActionDisableStrict: "Desactivar strict",
    emptyActionIncreaseDuration: "Aumentar duracion +60",
    emptyActionOpenRadius: "Abrir radio 150",
    emptyActionDateFlex: "Usar fechas cercanas (±2)",
    emptyActionClearExclusions: "Limpiar exclusiones",
    relaxToastPrefix: "Relajamos:",
    undoAction: "Deshacer",
    errorTitle: "No hemos podido completar la busqueda.",
    errorText: "Puedes reintentar en unos segundos.",
    errorRetry: "Reintentar",
    rateLimitTitle: "Demasiadas busquedas seguidas.",
    rateLimitText: "Espera unos segundos para volver a intentar.",
    rateLimitCountdown: "Podras buscar en",
    alternative: "Alternativo",
    itineraryDirect: "Directo",
    itinerarySelfConnect: "Self-connect",
    source: "Fuente",
    sourcesLabel: "Fuentes",
    sourcesDetailTitle: "Detalle de fuentes",
    sourcesDetailAria: "Ver detalle de fuentes de resultados",
    sourceUnknown: "Desconocida",
    save: "Guardar",
    viewWatchlist: "Ver Watchlist",
    watchExists: "Ya estaba guardado",
    stale: "dato desactualizado",
    lastData: "Ultimo dato",
    score: "Score",
    scoreHint: "Ranking heuristico",
    freshnessLabel: "Actualizado hace",
    freshnessStale: "Ultimo dato conocido",
    freshnessUnknown: "Sin datos de frescura",
    freshnessUnavailableGlobal: "Frescura no disponible",
    freshnessUnavailableTooltip: "No recibimos timestamp de frescura en esta respuesta.",
    detailsToggle: "Detalles",
    detailsHide: "Ocultar detalles",
    detailsLegs: "Tramos",
    detailsScore: "Desglose del score",
    detailsWindow: "Ventanas horarias",
    detailsAlt: "Alternativos y distancia",
    detailsBuffer: "Buffer entre tramos",
    detailsRisk: "Riesgo y margen",
    detailsNote: "La heuristica prioriza precio, tiempo y riesgo.",
    selectOutbound: "Selecciona una fecha de ida",
    selectReturn: "Selecciona una fecha de vuelta",
    selectReturnHint: "Selecciona una fecha de vuelta para completar ida y vuelta",
    returnBefore: "La fecha de vuelta no puede ser anterior a la ida",
    weatherError: "No se pudo cargar el clima para todas las fechas.",
    weatherUnavailableRange: "Clima no disponible para las fechas seleccionadas.",

    searchFailed: "No se pudo buscar.",
    noFlights: "No hay vuelos disponibles para esa fecha.",
    watchAdded: "Vuelo anadido a la watchlist",
    watchFailed: "No se pudo anadir a watchlist.",
    deepLinkError: "No se pudo generar el deep-link automatico.",
    noResults: "Sin resultados.",
    truncated: "Resultados truncados para mantener la busqueda rapida.",
    warnings: {
      stops_no_disponible_en_modo_rapido: "Las escalas no estan disponibles en la busqueda rapida.",
      origen_no_disponible_en_catalogo: "El origen no tiene catalogo de aeropuertos cercanos.",
      destino_no_disponible_en_catalogo: "El destino no tiene catalogo de aeropuertos cercanos.",
      limite_combinaciones_alternativas: "Se limitaron combinaciones para mantener la busqueda rapida.",
      ryanair_unavailable_parcial: "Algunas combinaciones no pudieron consultarse.",
      ryanair_unavailable_partial: "Algunas combinaciones no pudieron consultarse.",
      ryanair_availability_failed_partial: "No pudimos confirmar toda la disponibilidad de Ryanair; mostramos tarifas directas que si respondieron.",
      ryanair_fares_failed_partial: "No pudimos confirmar todas las tarifas directas de Ryanair; mostramos resultados confirmados por disponibilidad.",
      ryanair_availability_failed: "La consulta completa de Ryanair no respondio.",
      ryanair_fares_failed: "La consulta rapida de tarifas de Ryanair no respondio.",
      ryanair_provider_unavailable_total: "Ryanair no respondio y no pudimos confirmar vuelos en este momento.",
    },
  },
  en: {
    back: "Back",
    title: "Quick Search",
    subtitle: "Find routes and save opportunities to your watchlist.",
    titleRecommendations: "Recommendations",
    subtitleRecommendations: "Pick countries and see routes ranked by value.",
    workspaceHint: "Search workspace with filters, explainable ranking, and country picker.",
    workspaceHintRecommendations: "Pick countries or airports and refine with advanced filters if needed.",
    originLabel: "Origin (IATA)",
    originTip: "3-letter IATA airport code.",
    originHelp: "Type the code or use the country picker.",
    iataHelp: "Valid format: 3 letters (e.g. MAD).",
    iataInvalid: "IATA code must be 3 letters.",
    originRequired: "Enter an origin or choose an airport/country.",
    destinationRequired: "Enter a destination or choose an airport/country.",
    iataSuggest: "Pick a suggestion to avoid IATA code errors.",
    destinationLabel: "Destination (IATA)",
    destinationTip: "If there are multiple options, try a nearby alternative.",
    destinationHelp: "Type the code or use the country picker.",
    placeholderOrigin: "City or airport",
    placeholderDestination: "City or airport",
    placeholderDates: "Select dates",
    pickAirport: "Choose airport",
    pickAirportOriginAria: "Choose origin airport",
    pickAirportDestinationAria: "Choose destination airport",
    pickCountryOnly: "Use all {country}",
    pickCountryOnlyHint: "If you choose a country without an airport, we search all airports in that country.",
    countryOnlySelected: "Country selected: {country}",
    countryOnlyClear: "Clear country",
    pickRecent: "Recent",
    pickSearch: "Search airport or city",
    pickEmpty: "No results for that term.",
    pickClose: "Close",
    flexTitle: "How much date flexibility do you have?",
    daysBefore: "Days before",
    daysAfter: "Days after",
    exactDate: "Exact date",
    flexible: "Flexible",
    flexHelper: "Pick a quick option first and fine-tune only if you need it.",
    flexHelperExact: "We will search only on the selected date.",
    flexHelperFlexible: "We will search nearby departure dates to surface more options.",
    flexHelperCustom: "Adjust how many days before and after you want to explore.",
    flexPresetExact: "Exact",
    flexPresetOne: "±1 day",
    flexPresetTwo: "±2 days",
    flexPresetThree: "±3 days",
    flexPresetCustom: "Customize",
    flexCustomSummary: "Custom · -{before} / +{after} days",
    flexBeforeControl: "Search from",
    flexAfterControl: "Search until",
    flexApplyReturn: "Use this same date range for the return",
    dateLabel: "Date",
    dateTip: "Pick the exact departure date.",
    roundTrip: "Round trip",
    returnLabel: "Return",
    passengers: "Adult passengers",
    search: "Search",
    searchHintRouteInvalid: "Enter valid Origin and Destination to search",
    searchHintNeedDate: "Select an outbound date to search",
    ready: "Ready to search",
    searchReadyTitle: "Ready to explore",
    searchReadyText: "Enter a route and hit Search to see opportunities.",
    searchReadyHint: "Expand with nearby airports and +/- days if no results.",
    quickLookTitle: "Quick start",
    quickLookBody: "Set route, dates, and filters, then press Search to explore opportunities.",
    quickLookAcknowledge: "Got it",
    autocompleteSuggestionsAvailable: "{count} suggestions available",
    autocompleteNoSuggestions: "No suggestions",
    summaryPassengersSingular: "passenger",
    summaryPassengersPlural: "passengers",
    summaryRoundTrip: "Round trip",
    summaryRoundTripMissingReturn: "Round trip (return missing)",
    summaryOneWay: "One way",
    summaryRadius: "radius",
    summaryStrictOn: "Strict enabled",
    summaryStrictOff: "Strict disabled",
    summaryDurationMax: "Max duration",
    summaryDurationOpen: "Duration open",
    summaryExclusions: "Exclusions",
    summaryMissingOrigin: "Origin missing",
    summaryMissingDestination: "Destination missing",
    summaryMissingDate: "Date missing",
    searchSummaryTitle: "Search summary",
    appliedCriteriaTitle: "Applied criteria",
    pendingChangesTitle: "Unapplied changes",
    pendingChangesBody: "Press Search to refresh results with your current criteria.",
    applyAndSearch: "Apply and search",
    filtersTitle: "Advanced filters",
    filtersSubtitle: "Adjust time windows, risk, and rules before searching.",
    filtersMicrocopy: "Tip: if empty, try nearby dates and a nearby airport.",
    filterConsoleEyebrow: "Filter control",
    filterConsoleTitle: "Search console",
    filterConsoleSubtitle: "Decide how wide the search should go and which returned results should stay visible.",
    filterCountLabel: "active",
    filterNoActive: "No extra filters: direct search, broad time window, and complete result view.",
    filterAppliedOnSearch: "Applies on search",
    filterAppliedToResults: "Adjusts the view",
    filterPartialSupport: "Partial support",
    filterCoverageDirect: "Base route only",
    filterVisibleOpen: "Open view",
    filterVisibleCustom: "Tuned view",
    filterExperimentalOn: "Self-connect on",
    filterExperimentalOff: "Direct first",
    coverageTitle: "Coverage",
    coverageBody: "Open or limit alternate airports and exclude IATA codes you do not want to use.",
    visibleResultsTitle: "Visible results",
    visibleResultsBody: "Filter and sort returned results without changing the backend contract.",
    filterPresetDirect: "Direct",
    filterPresetDirectHint: "Exact origin and destination.",
    filterPresetOriginNearby: "Open origin",
    filterPresetOriginNearbyHint: "Search alternates near the origin.",
    filterPresetBothNearby: "Open both",
    filterPresetBothNearbyHint: "Explore nearby origins and destinations.",
    filterPresetRegional: "Regional",
    filterPresetRegionalHint: "Wider radius for more combinations.",
    resetGroup: "Reset group",
    appliedPref: "Applied from your preferences",
    alternatesTitle: "Alternatives and coverage",
    radiusLabel: "Alternate radius (km)",
    radiusHint: "Include nearby airports; higher values may slow the search.",
    radiusInactive: "Enable nearby origins or destinations to use radius.",
    priceMin: "Min price",
    priceMax: "Max price",
    nearbyOrigins: "Include nearby origins",
    nearbyDestinations: "Include nearby destinations",
    timeTitle: "Time and viability",
    timeSubtitle: "Control time windows and total duration.",
    departAfter: "Depart after",
    departBefore: "Depart before",
    durationMax: "Max duration (min)",
    strictMode: "Strict mode (no relaxation)",
    strictWarning: "Viru can relax time windows if there are no results. Disable to explore more options.",
    stopsTitle: "Stops and exclusions",
    stopsSubtitle: "Self-connect requires buffer time.",
    includeStops: "Include stops (self-connect)",
    maxStops: "Max stops",
    riskAllowed: "Allowed risk",
    bufferMin: "Minimum buffer (min)",
    bufferMinHint: "Recommended margin between legs.",
    excludeOrigins: "Exclude origins (IATA)",
    excludeDestinations: "Exclude destinations (IATA)",
    selfConnectWarning: "Self-connect: check buffer time and risk before buying.",
    resetPrefs: "Reset to my preferences",
    resetAll: "Reset all",
    deepLink: "Open in Ryanair",
    deepLinkAlt: "Copy parameters",
    deepLinkModalTitle: "No direct link",
    deepLinkModalBody: "We could not generate a direct link. Copy the search or open Ryanair manually.",
    deepLinkCopy: "Copy parameters",
    deepLinkCopied: "Parameters copied",
    loadingFlight: "loading flight",
    loadingAria: "Loading",
    loadingTitle: "Searching opportunities",
    loadingText: "Trying alternatives and flexible dates.",
    loadingPhaseRequesting: "Checking fares...",
    loadingPhaseResponseParsed: "Sorting results...",
    loadingPhaseClientDone: "Preparing view...",
    loadingPhaseCommitted: "Ready",
    loadingSubcheckTitle: "Checks in progress",
    loadingSubcheckFlight: "Searching flight {route}",
    loadingSubcheckCombo: "Searching best combination {index}/{total}",
    loadingSubcheckActive: "in progress",
    loadingSubcheckDone: "done",
    loadingTotalFlights: "Flights to scan: {count}",
    loadingProgressFlights: "Progress: {current}/{total} flights",
    loadingScope: "Live scope: {routes} routes x {days} days",
    modalOriginCountry: "Origin country",
    modalDestinationCountry: "Destination country",
    modalPickTitle: "Choose airport",
    modalClear: "Clear selection",
    weatherTitle: "Weather forecast",
    weatherSubtitle: "Origin and destination for each selected date",
    weatherOrigin: "Origin",
    weatherDestination: "Destination",
    weatherDepart: "Departure",
    weatherArrive: "Arrival",
    weatherClear: "Clear",
    weatherMostlyClear: "Mostly clear",
    weatherCloudy: "Cloudy",
    weatherFog: "Fog",
    weatherDrizzle: "Drizzle",
    weatherRain: "Rain",
    weatherSnow: "Snow",
    weatherShowers: "Showers",
    weatherStorm: "Storm",
    weatherVariable: "Variable",
    explainTitle: "How we rank",
    explainSubtitle: "Heuristic ranking based on price, date deviation, distance, and risk.",
    explainPriceTitle: "Price",
    explainTimeTitle: "Date deviation",
    explainAltTitle: "Alternatives",
    explainRiskTitle: "Risk",
    explainPrice: "Prioritizes opportunities with better relative value.",
    explainTime: "Closer to your target date.",
    explainAlt: "Ground distance and access effort.",
    explainRisk: "Self-connect with low buffer lowers priority.",
    disclaimer: "Quick search in heuristic mode. Indicative base price for 1 adult without extras.",
    disclaimerWatchlistCta: "Save to watchlist for price changes.",
    degraded: "Provider temporarily unavailable. Showing last confirmed data.",
    degradedBadge: "Degraded mode",
    degradedChip: "Heuristic",
    degradedHint: "If the provider is down, we show the last confirmed data.",
    filtersRelaxed: "Filters relaxed",
    relaxedDateFlexAuto: "automatic date flexibility",
    relaxedNearbyAuto: "automatic nearby-airport expansion",
    relaxedDepartureWindowAuto: "automatically expanded departure window",
    results: "results",
    orderedBy: "sorted by",
    orderBy: "Sort by",
    toolbarFilters: "Filters",
    toolbarExplain: "How we rank",
    toolbarCompact: "Compact view",
    toolbarExpanded: "Detailed view",
    toolbarActiveFilters: "Active filters",
    infoSectionTitle: "Information",
    viewDetail: "View detail",
    warningDetailsOpen: "View details",
    warningDetailsClose: "Hide details",
    warningsGroupedTitle: "Warnings",
    warningProblemTitle: "Problem",
    providerPartialAvailabilityNotice: "Showing confirmed results, but some Ryanair availability checks did not respond.",
    providerPartialFaresNotice: "Showing confirmed results, but some Ryanair fare checks did not respond.",
    providerPartialMixedNotice: "Showing confirmed results, but Ryanair only partially responded in this search.",
    emptyStateMainTitle: "0 results with these filters",
    emptyStateProviderTitle: "Ryanair is not responding right now",
    emptyStateProviderPartialTitle: "Partial search: Ryanair did not fully respond",
    emptyShowMore: "Show more",
    emptyShowLess: "Show less",
    rowActionsMoreAria: "Open more actions",
    rowActionsMenuAria: "Additional result actions",
    ariaFiltersToggle: "Filters ({count})",
    ariaRemoveFilter: "Remove {value}",
    resultsColRoute: "Route",
    resultsColPrice: "Price",
    resultsColDuration: "Duration",
    resultsColRisk: "Risk",
    resultsColFreshness: "Freshness",
    resultsColActions: "Actions",
    sortRanking: "Ranking",
    sortPrice: "Price",
    sortDuration: "Duration",
    sortRisk: "Risk",
    sortFreshness: "Freshness",
    sortFreshnessHint: "Latest update",
    riskAll: "All",
    riskLow: "Low",
    riskMedium: "Medium",
    riskHigh: "High",
    riskHidden: "Hidden (high risk)",
    riskShowHidden: "Show high risk",
    riskHideHidden: "Hide high risk",
    stopsOne: "1 stop",
    stopsTwo: "2 stops",
    startSearch: "Run a search to see opportunities.",
    noResultsFilters: "No results with these filters.",
    relaxFilters: "Relax filters",
    emptyTitle: "No results with these filters.",
    emptyText: "Try relaxing restrictions or expanding the radius.",
    stateEmptyHint: "Adjust filters or use a quick relax action to recover results.",
    stateErrorHint: "Review form inputs and try again.",
    stateRateHint: "Requests are temporarily limited to protect the service.",
    emptyCta: "Relax filters",
    relaxPreviewTitle: "Proposed changes",
    relaxPreviewImpact: "These changes may show more results.",
    relaxPreviewConfirm: "Apply changes and search",
    relaxPreviewCancel: "Cancel",
    relaxPreviewNoChanges: "No changes are needed with the current settings.",
    emptyLikelyCausesTitle: "Likely causes",
    emptyRelaxActionsTitle: "Quick relax",
    emptyCauseStrict: "Strict mode is enabled (no relaxation).",
    emptyCauseDuration: "Max duration may be filtering valid routes.",
    emptyCauseTimeWindow: "The departure time window is narrow.",
    emptyCauseRadius: "Alternate-airport radius is limited.",
    emptyCauseExclusions: "Excluded airports are reducing options.",
    emptyCauseStops: "Stops are disabled (direct only).",
    emptyCauseProvider: "The provider did not respond, so we could not confirm flights right now.",
    emptyActionDisableStrict: "Disable strict",
    emptyActionIncreaseDuration: "Increase duration +60",
    emptyActionOpenRadius: "Open radius 150",
    emptyActionDateFlex: "Use nearby dates (±2)",
    emptyActionClearExclusions: "Clear exclusions",
    relaxToastPrefix: "Relaxed:",
    undoAction: "Undo",
    errorTitle: "We couldn't complete the search.",
    errorText: "Try again in a few seconds.",
    errorRetry: "Retry",
    rateLimitTitle: "Too many searches in a row.",
    rateLimitText: "Wait a few seconds before trying again.",
    rateLimitCountdown: "You can search in",
    alternative: "Alternative",
    itineraryDirect: "Direct",
    itinerarySelfConnect: "Self-connect",
    source: "Source",
    sourcesLabel: "Sources",
    sourcesDetailTitle: "Source details",
    sourcesDetailAria: "View source details for results",
    sourceUnknown: "Unknown",
    save: "Save",
    viewWatchlist: "View Watchlist",
    watchExists: "Already saved",
    stale: "stale",
    lastData: "Last data",
    score: "Score",
    scoreHint: "Heuristic ranking",
    freshnessLabel: "Updated",
    freshnessStale: "Last known data",
    freshnessUnknown: "No freshness data",
    freshnessUnavailableGlobal: "Freshness unavailable",
    freshnessUnavailableTooltip: "No freshness timestamp was returned in this response.",
    detailsToggle: "Details",
    detailsHide: "Hide details",
    detailsLegs: "Legs",
    detailsScore: "Score breakdown",
    detailsWindow: "Time windows",
    detailsAlt: "Alternatives & distance",
    detailsBuffer: "Connection buffer",
    detailsRisk: "Risk and margin",
    detailsNote: "Heuristic prioritizes price, time, and risk.",
    selectOutbound: "Select an outbound date",
    selectReturn: "Select a return date",
    selectReturnHint: "Select a return date to complete round trip",
    returnBefore: "Return date cannot be earlier than outbound",
    weatherError: "Weather data could not be loaded for all dates.",
    weatherUnavailableRange: "Weather unavailable for the selected dates.",
    searchFailed: "Search failed.",
    noFlights: "No flights available for that date.",
    watchAdded: "Flight added to watchlist",
    watchFailed: "Could not add to watchlist.",
    deepLinkError: "Could not generate the deep-link automatically.",
    noResults: "No results.",
    truncated: "Results were truncated to keep quick search fast.",
    warnings: {
      stops_no_disponible_en_modo_rapido: "Stops are not available in quick search.",
      origen_no_disponible_en_catalogo: "Origin has no nearby airport catalog.",
      destino_no_disponible_en_catalogo: "Destination has no nearby airport catalog.",
      limite_combinaciones_alternativas: "Combinations were limited to keep quick search fast.",
      ryanair_unavailable_parcial: "Some combinations could not be queried.",
      ryanair_unavailable_partial: "Some combinations could not be queried.",
      ryanair_availability_failed_partial: "Some Ryanair availability checks failed; showing direct fares that did respond.",
      ryanair_fares_failed_partial: "Some Ryanair fare checks failed; showing results confirmed by availability.",
      ryanair_availability_failed: "Ryanair full availability did not respond.",
      ryanair_fares_failed: "Ryanair fare lookup did not respond.",
      ryanair_provider_unavailable_total: "Ryanair did not respond and we could not confirm flights right now.",
    },
  },
} as const;

type QuickSearchCopyMap = typeof QUICK_SEARCH_COPY.es;
type QuickSearchWarnings = QuickSearchCopyMap["warnings"];
export type QuickSearchCopyKey = Exclude<keyof QuickSearchCopyMap, "warnings">;

export function resolveQuickSearchLocale(raw?: string | null): QuickSearchLocale {
  if (raw && raw.toLowerCase().startsWith("en")) return "en";
  return "es";
}

export function getQuickSearchCopy(raw?: string | null) {
  const locale = resolveQuickSearchLocale(raw);
  const copy = QUICK_SEARCH_COPY[locale];
  const fallback = QUICK_SEARCH_COPY.es;
  const t = (key: QuickSearchCopyKey): string => copy[key] ?? fallback[key] ?? String(key);
  const warnings = copy.warnings as Record<keyof QuickSearchWarnings, string>;
  const fallbackWarnings = fallback.warnings as Record<keyof QuickSearchWarnings, string>;
  const tWarn = (code: string): string => {
    const typedCode = code as keyof QuickSearchWarnings;
    return warnings[typedCode] ?? fallbackWarnings[typedCode] ?? code;
  };
  const localeTag = locale === "en" ? "en-US" : "es-ES";
  return { locale, localeTag, t, tWarn };
}
