WATCH_STATUS_ACTIVE = "active"
WATCH_STATUS_PAUSED = "paused"
WATCH_STATUS_DELETED = "deleted"
WATCH_STATUS_VALUES = (
    WATCH_STATUS_ACTIVE,
    WATCH_STATUS_PAUSED,
    WATCH_STATUS_DELETED,
)
WATCH_STATUS_UPDATABLE = (
    WATCH_STATUS_ACTIVE,
    WATCH_STATUS_PAUSED,
)

ALERT_RULE_TYPE_THRESHOLD_LOW = "threshold_low"
ALERT_RULE_TYPE_THRESHOLD_HIGH = "threshold_high"
ALERT_RULE_TYPE_EVERY_CHANGE = "every_change"
RULE_TYPE_ALIASES = {
    "threshold_below": ALERT_RULE_TYPE_THRESHOLD_LOW,
    "threshold_above": ALERT_RULE_TYPE_THRESHOLD_HIGH,
}
ALLOWED_RULE_TYPES = {
    ALERT_RULE_TYPE_THRESHOLD_LOW,
    ALERT_RULE_TYPE_THRESHOLD_HIGH,
    ALERT_RULE_TYPE_EVERY_CHANGE,
    *RULE_TYPE_ALIASES.keys(),
}

DELIVERY_STATUS_QUEUED = "queued"
DELIVERY_STATUS_SENT = "sent"
DELIVERY_STATUS_DELIVERED = "delivered"
DELIVERY_STATUS_FAILED = "failed"
DELIVERY_STATUS_ERROR = "error"
DELIVERY_STATUS_VALUES = (
    DELIVERY_STATUS_QUEUED,
    DELIVERY_STATUS_SENT,
    DELIVERY_STATUS_DELIVERED,
    DELIVERY_STATUS_FAILED,
    DELIVERY_STATUS_ERROR,
)

SYSTEM_STATUS_OK = "ok"
SYSTEM_STATUS_DEGRADED = "degraded"
SYSTEM_STATUS_CRITICAL = "critical"
SYSTEM_STATUS_VALUES = (
    SYSTEM_STATUS_OK,
    SYSTEM_STATUS_DEGRADED,
    SYSTEM_STATUS_CRITICAL,
)
